### ISSUE TITLE
Pre-Training with MoCoV2

### ISSUE THREAD

**Issue by Gaotianhong** [Wolfda95/SSL-MedicalImagining-CL-MAE#1]
Thank you for great job!

 I'd like to pre-training with MoCoV2 on my dataset, but I could not find a bash script.

Could you add it in README.md?

**Comment by Wolfda95** [comment]
Hey, 

great that you are interested in our work and thank you for your question. 

You are right, we forgot to put a bash script for MoCo. Sorry for that. 
We added that now: [https://github.com/Wolfda95/SSL-MedicalImagining-CL-MAE/tree/main/Pre-Training/Contrastive_Learning](https://github.com/Wolfda95/SSL-MedicalImagining-CL-MAE/tree/main/Pre-Training/Contrastive_Learning) 

Your data needs to be .png or .jpeg files and when you enter the path to your data folder in  --data_dir in the bash file, the folder you put there needs to have a sub folder where the images are stored in. 

Let me know if you have further questions.
